theme = "rose_pine_moon"

[editor]
line-number = "relative"
mouse = false
auto-save = true
color-modes = true
bufferline = "multiple"
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding"]

[keys.normal]
y = "yank_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
d = ["yank_to_clipboard", "delete_selection"]

[keys.select]
y = "yank_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
d = ["yank_to_clipboard", "delete_selection"]
