#!/usr/bin/env bash

# zed-helix-keybinds.sh — searchable Zed helix-mode cheatsheet via rofi
# Place this at ~/.config/rofi/zed-helix-keybinds.sh
#
# NOTE: Zed's helix mode is built on top of vim mode. Most vanilla helix
# keybinds work, but some are mapped differently or use Zed-native actions.
# Anything marked [ZED] differs from standard helix behaviour.
# Anything marked [WIP] may not be implemented yet.

THEME="$HOME/.config/rofi/helix-keybinds.rasi"

entries=(
# ── CORE IDEA ─────────────────────────────────────────────────────────
"                    ── CORE IDEA ──"
"  motion → verb     select first, then act (opposite of vim)"
"  cursor            always a 1-char selection at rest"
"  Esc               collapse selection, back to normal"
"  ;                 collapse selection only (stay normal)"
# ── ENABLING ──────────────────────────────────────────────────────────
"                    ── ENABLING IN ZED ──"
"  settings.json     set \"helix_mode\": true  (also enables vim_mode)"
"  cmd palette       'toggle helix mode'"
# ── MODES ─────────────────────────────────────────────────────────────
"                    ── MODES ──"
"  i                 insert before selection"
"  a                 insert after selection"
"  I                 insert at line start"
"  A                 insert at line end"
"  o                 new line below, enter insert"
"  O                 new line above, enter insert"
"  Esc               back to normal mode"
# ── MOVEMENT ──────────────────────────────────────────────────────────
"                    ── MOVEMENT ──"
"  h j k l           left / down / up / right"
"  w                 next word start (and selects it)"
"  b                 prev word start (and selects it)"
"  e                 word end (and selects it)"
"  W B E             same but WORD (ignores punctuation)"
"  0                 line start"
"  ^                 first non-space on line"
"  \$                 line end"
"  gg                top of file"
"  ge                bottom of file"
"  G                 go to line number"
"  Ctrl+d            half page down"
"  Ctrl+u            half page up"
"  %                 select entire file"
"  zz / zt / zb      center / top / bottom screen"
# ── FIND ON LINE ──────────────────────────────────────────────────────
"                    ── FIND ON LINE ──"
"  fx                select to next 'x' on line"
"  Fx                select to prev 'x' on line"
"  tx                select till next 'x' (stops before)"
"  Tx                select till prev 'x'"
# ── LINE SELECTION ────────────────────────────────────────────────────
"                    ── LINE SELECTION ──"
"  x                 select current line"
"  x x x             extend selection line by line"
"  X                 extend selection to full lines"
"  Alt+;             flip selection direction (swap anchor)"
"  ;                 collapse selection to cursor"
"  ,                 keep only primary selection (drop extras)"
"  Alt+,             remove primary selection"
# ── MATCH OBJECTS ─────────────────────────────────────────────────────
"                    ── MATCH OBJECTS (select inside / around) ──"
"  mi(               select inside parentheses"
"  mi[               select inside square brackets"
"  mi{               select inside curly braces"
"  mi\"               select inside double quotes"
"  mi'               select inside single quotes"
"  miw               select inner word"
"  mip               select inner paragraph"
"  ma(               select around parens (includes parens)"
"  ma\"               select around quotes (includes quotes)"
"  mm                jump to matching bracket"
"  [ZED] ] (         select NEXT pair of parens after cursor"
"  [ZED] [ (         select PREV pair of parens before cursor"
"  [ZED] ] m / [ m   go to next / prev function / method"
"  [ZED] ] ] / [ [   go to next / prev class / section"
"  [ZED] ] d / [ d   go to next / prev diagnostic"
"  [ZED] ] c / [ c   go to next / prev git change hunk"
# ── SURROUND ──────────────────────────────────────────────────────────
"                    ── SURROUND ──"
"  ms(               surround selection with ()"
"  ms\"               surround selection with \"\""
"  ms{               surround selection with {}"
"  md(               delete surrounding ()"
"  md\"               delete surrounding \"\""
"  mr(\"              replace () with \"\""
# ── EDITING ───────────────────────────────────────────────────────────
"                    ── EDITING ──"
"  d                 delete selection"
"  Alt+d             delete without yanking (safe delete)"
"  c                 change selection (delete + insert)"
"  r                 replace each char in selection"
"  ~                 swap case of selection"
"  \`                 lowercase selection"
"  Alt+\`             uppercase selection"
"  >                 indent selection right"
"  <                 indent selection left"
"  =                 auto-format/align indent"
"  J                 join selected lines"
"  u                 undo"
"  U                 redo"
"  .                 repeat last change"
# ── COPY & PASTE ──────────────────────────────────────────────────────
"                    ── COPY & PASTE ──"
"  y                 yank (copy) selection  [no sel = yank char under cursor]"
"  p                 paste after selection"
"  P                 paste before selection"
"  R                 replace selection with yanked text"
"  x y p             duplicate line (select line, yank, paste)"
# ── SEARCH ────────────────────────────────────────────────────────────
"                    ── SEARCH ──"
"  /word Enter       search forward"
"  ?word Enter       search backward"
"  n / N             next / prev match (extends selection)"
"  *                 search word under cursor ↓"
"  #                 search word under cursor ↑"
"  s (in selection)  split selection into per-match cursors"
# ── MULTIPLE CURSORS ──────────────────────────────────────────────────
"                    ── MULTIPLE CURSORS ──"
"  C                 add cursor below (copy selection down)"
"  Alt+C             add cursor above"
"  s                 select regex within selection → each match = cursor"
"  S                 split selection on regex"
"  Alt+s             split selection on newlines"
"  % then s          select whole file then split by regex"
"  )                 rotate primary selection forward"
"  (                 rotate primary selection backward"
"  ,                 keep only primary, remove extras"
"  [ZED] g l         add cursor selecting NEXT occurrence of current word"
"  [ZED] g L         add cursor selecting PREV occurrence of current word"
"  [ZED] g a         select ALL occurrences of current word (visual)"
"  [ZED] g >         skip latest word selection, add next"
"  [ZED] g <         skip latest word selection, add prev"
# ── SPACE MENU ────────────────────────────────────────────────────────
"                    ── SPACE MENU (helix) / ZED EQUIVALENTS ──"
"  Space+f           file picker  (≈ Ctrl+P in default Zed)"
"  Space+b           buffer picker  (≈ tab switcher)"
"  Space+/           global project search"
"  Space+s           symbol picker (current file)"
"  [ZED] g s         symbol in current file  (helix: Space+s)"
"  [ZED] g S         symbol in whole project  (helix: Space+S)"
"  [ZED] g .         code actions  (helix: Space+a)"
"  [ZED] c d         rename symbol  (helix: Space+r)"
"  [ZED] g h         hover / inline docs  (helix: Space+h / K)"
"  [ZED] g /         open project-wide search pane"
# ── GOTO (g) ──────────────────────────────────────────────────────────
"                    ── GOTO COMMANDS ──"
"  g d               go to definition"
"  g D               go to declaration"
"  g y               go to type definition"
"  g I               go to implementation"
"  g A               go to all references  [ZED: adds cursors in visual]"
"  g g               file start  (same as gg)"
"  g e               file end"
"  g h               show inline error / hover docs  [ZED]"
"  g ]  / g [        next / prev diagnostic  [ZED]"
"  g .               open code actions menu  [ZED]"
# ── LSP / LANGUAGE SERVER ─────────────────────────────────────────────
"                    ── LSP FEATURES ──"
"  g d               go to definition"
"  g D               go to declaration"
"  g y               go to type definition"
"  g I               go to implementation"
"  c d               rename symbol  [ZED — helix uses Space+r]"
"  g .               code actions  [ZED — helix uses Space+a]"
"  g h               hover docs  [ZED — helix uses K]"
# ── TREE-SITTER TEXT OBJECTS ──────────────────────────────────────────
"                    ── TREE-SITTER TEXT OBJECTS [ZED] ──"
"  a c / i c         around / inside class or definition"
"  a f / i f         around / inside function or method"
"  a a / i a         around / inside argument or list item"
"  a t / i t         around / inside HTML-like tag"
"  g c               comment object  (also: gcc to toggle comment)"
"  a I / a i / i i   around / inside indent levels"
# ── WINDOWS & SPLITS ──────────────────────────────────────────────────
"                    ── WINDOWS & SPLITS ──"
"  Ctrl+w v          vertical split  (or :vs)"
"  Ctrl+w s          horizontal split  (or :sp)"
"  Ctrl+w h/j/k/l    move between splits"
"  Ctrl+w q          close split  (or :q)"
"  Ctrl+w Space      open current search excerpt in split  [ZED]"
"  Ctrl+w g d        go to definition in split  [ZED]"
# ── FILE & BUFFER COMMANDS ────────────────────────────────────────────
"                    ── FILE & BUFFER COMMANDS ──"
"  :w                save"
"  :q                close buffer"
"  :wq               save and close"
"  :wa               save all open files"
"  :qa               close all buffers"
"  :vs               vertical split"
"  :sp               horizontal split"
"  :bd               close active file in all panes"
"  :tabn / :tabp     next / prev tab"
"  :<number>         jump to line number"
"  :\$                jump to end of file"
"  :/foo             jump to next line matching foo"
"  :[range]s/a/b/g   substitute (Zed regex — see note below)"
# ── ZED COMMAND PALETTE ───────────────────────────────────────────────
"                    ── ZED COMMAND PALETTE & EX COMMANDS ──"
"  :                 open Zed command palette (any Zed action)"
"  :E[xplore]        open project panel"
"  :G[it]            open git panel"
"  :te[rm]           open terminal"
"  :cl[ist]          open diagnostics window"
"  :A[I]             open AI / agent panel"
"  :Ext[ensions]     open extensions window"
# ── REGEX NOTE ────────────────────────────────────────────────────────
"                    ── REGEX DIFFERENCES (Zed vs vanilla helix) ──"
"  capture groups    Zed uses ( ) not \\( \\)"
"  back-references   Zed uses \$1 not \\1"
"  global replace    add /g flag  (Zed is NOT global by default)"
"  case-insensitive  use (?i) prefix instead of /i flag"
# ── ZED-ONLY KEYBINDS ─────────────────────────────────────────────────
"                    ── ZED-SPECIFIC ADDITIONS ──"
"  Ctrl+x Ctrl+o     open completion menu (insert mode)"
"  Ctrl+x Ctrl+a     open inline AI assistant (insert mode)"
"  Ctrl+x Ctrl+l     open code actions menu (insert mode)"
"  d o               expand diff hunk (git)"
"  d p               restore / revert diff hunk (git)"
"  g R               replace with register (ReplaceWithRegister)"
"  c x               exchange operator (vim-exchange)"
"  g c               toggle comment (gcc = current line)"
)

printf '%s\n' "${entries[@]}" | rofi \
    -dmenu \
    -p "󰨞 zed helix" \
    -theme "$THEME" \
    -no-custom \
    -i \
    -no-fixed-num-lines \
    -selected-row 0
