#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
exec-once = hyprpaper
exec-once = $menuBar
exec-once = gnome-keyring-daemon --start --components=secrets,ssh,pkcs11
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# exec-once = spotify
exec-once = anyrun daemon
exec-once = nm-applet &
# exec-once = swaync
# exec-once = quickshell -p ~/.config/quickshell/media
# exec-once = caelestia shell -d
